#!/usr/bin/env python3
"""Pack the card and action-space artwork in ../resource/ into game/cardimages.js.

The game runs from file://, where an SVG texture cannot load an external PNG and a
file:// image would taint the WebGL canvas, so each picture is shrunk to a 512 px JPEG
and embedded as a data URI. A file is matched to a card by its English name with
spaces and punctuation removed: "animaltamer.png" -> "Animal Tamer".

Run from anywhere:  python3 game/tools/build_card_images.py
Needs macOS `sips` for the resize.
"""
import base64, json, os, re, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC = os.path.join(ROOT, 'resource')
OUT = os.path.join(ROOT, 'game', 'cardimages.js')
KINDS = ['occupation', 'minor', 'minorimprovement', 'major', 'majorimprovement']
SIZE, QUALITY = 512, 80

def key(s):
    return re.sub(r'[^a-z0-9]', '', s.lower())

def card_names():
    text = open(os.path.join(ROOT, 'data.js'), encoding='utf-8').read()
    names = {}
    for _q, m in re.findall(r"""en:(['"])((?:(?!\1)[^\\]|\\.)*)\1""", text):
        en = m.replace("\\'", "'").replace('\\"', '"')
        names[key(en)] = en
        names.setdefault(key(re.sub(r"'s\b", '', en)), en)   # basketmakerworkshop -> Basketmaker's Workshop
    return names

def encode(path):
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, 'x.jpg')
        subprocess.run(['sips', '-Z', str(SIZE), '-s', 'format', 'jpeg',
                        '-s', 'formatOptions', str(QUALITY), path, '--out', out],
                       check=True, capture_output=True)
        return 'data:image/jpeg;base64,' + base64.b64encode(open(out, 'rb').read()).decode()

def main():
    names = card_names()
    found, unmatched = {}, []
    for kind in KINDS:
        folder = os.path.join(SRC, kind)
        if not os.path.isdir(folder):
            continue
        for f in sorted(os.listdir(folder)):
            base, ext = os.path.splitext(f)
            if ext.lower() not in ('.png', '.jpg', '.jpeg', '.webp'):
                continue
            en = names.get(key(base))
            if not en:
                unmatched.append(f'{kind}/{f}')
                continue
            found[en] = encode(os.path.join(folder, f))
            print(f'  {kind}/{f} -> {en} ({len(found[en]) * 3 // 4 // 1024} KB)')
    # Action spaces, keyed by space id, matched on the space's English name or its id.
    spaces = {}
    eng = open(os.path.join(ROOT, 'game', 'engine.js'), encoding='utf-8').read()
    for sid, en in re.findall(r"id:\s*'([a-z_0-9]+)',\s*en:\s*'([^']+)'", eng):
        spaces[key(en)] = sid
        spaces[key(sid)] = sid
    actions = {}
    folder = os.path.join(SRC, 'action')
    for f in sorted(os.listdir(folder)) if os.path.isdir(folder) else []:
        base, ext = os.path.splitext(f)
        if ext.lower() not in ('.png', '.jpg', '.jpeg', '.webp'):
            continue
        sid = spaces.get(key(base))
        if not sid:
            unmatched.append(f'action/{f}')
            continue
        actions[sid] = encode(os.path.join(folder, f))
        print(f'  action/{f} -> {sid} ({len(actions[sid]) * 3 // 4 // 1024} KB)')

    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('// Generated by tools/build_card_images.py — do not edit by hand.\n')
        fh.write('// Card artwork keyed by English card name, as embedded JPEG data URIs.\n')
        fh.write('const CARD_IMAGES = ' + json.dumps(found, indent=0) + ';\n')
        fh.write('// Action space artwork keyed by space id.\n')
        fh.write('const ACTION_IMAGES = ' + json.dumps(actions, indent=0) + ';\n')
    print(f'wrote {OUT}: {len(found)} card images, {len(actions)} action images')
    if unmatched:
        print('no card matched:', ', '.join(unmatched), file=sys.stderr)

if __name__ == '__main__':
    main()
