#!/usr/bin/env python3
"""Pack the card artwork in ../resource/<kind>/ into game/cardimages.js.

The game runs from file://, where an SVG texture cannot load an external PNG and a
file:// image would taint the WebGL canvas, so each picture is shrunk to a 512 px JPEG
and embedded as a data URI. A file is matched to a card by its English name with
spaces and punctuation removed: "animaltamer.png" -> "Animal Tamer".

Run from anywhere:  python3 game/tools/build_card_images.py
Needs macOS `sips` for the resize.
"""
import base64, json, os, re, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC = os.path.join(ROOT, 'resource')
OUT = os.path.join(ROOT, 'game', 'cardimages.js')
KINDS = ['occupation', 'minor', 'major']
SIZE, QUALITY = 512, 80

def key(s):
    return re.sub(r'[^a-z0-9]', '', s.lower())

def card_names():
    text = open(os.path.join(ROOT, 'data.js'), encoding='utf-8').read()
    return {key(m): m for m in re.findall(r"en:'((?:[^'\\]|\\.)*)'", text)}

def main():
    names = card_names()
    found, unmatched = {}, []
    for kind in KINDS:
        folder = os.path.join(SRC, kind)
        if not os.path.isdir(folder):
            continue
        for f in sorted(os.listdir(folder)):
            base, ext = os.path.splitext(f)
            if ext.lower() not in ('.png', '.jpg', '.jpeg', '.webp'):
                continue
            en = names.get(key(base))
            if not en:
                unmatched.append(f'{kind}/{f}')
                continue
            with tempfile.TemporaryDirectory() as tmp:
                out = os.path.join(tmp, 'x.jpg')
                subprocess.run(['sips', '-Z', str(SIZE), '-s', 'format', 'jpeg',
                                '-s', 'formatOptions', str(QUALITY), os.path.join(folder, f), '--out', out],
                               check=True, capture_output=True)
                data = base64.b64encode(open(out, 'rb').read()).decode()
            found[en] = 'data:image/jpeg;base64,' + data
            print(f'  {kind}/{f} -> {en} ({len(data) // 1024} KB)')
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('// Generated by tools/build_card_images.py — do not edit by hand.\n')
        fh.write('// Card artwork keyed by English card name, as embedded JPEG data URIs.\n')
        fh.write('const CARD_IMAGES = ' + json.dumps(found, indent=0) + ';\n')
    print(f'wrote {OUT}: {len(found)} images')
    if unmatched:
        print('no card matched:', ', '.join(unmatched), file=sys.stderr)

if __name__ == '__main__':
    main()
