// Agricola (Revised Edition, 2016) — full base-game card list
// 48 Occupations + 48 Minor Improvements + 10 Major Improvements
// type: occ | min | maj   deck: A | B (as printed on the cards)   p: minimum players
// cost: {resource: n}     vp: printed victory points     trav: traveling card (pass left after playing)
const CARDS = [
  // ============ OCCUPATIONS (48) ============
  {type:'occ', deck:'A', p:4, en:'Conjurer', zh:'魔術師',
   txt:'Each time you use the "Traveling Players" accumulation space, you get an additional 1 wood and 1 grain.',
   txz:'每次你使用「巡迴藝人」累積格時，額外獲得1木材和1穀物。'},
  {type:'occ', deck:'A', p:3, en:'Harpooner', zh:'魚叉手',
   txt:'Each time you use the "Fishing" accumulation space, you can also pay 1 wood to get 1 food for each person you have, and 1 reed.',
   txz:'每次你使用「捕魚」累積格時，你可以額外支付1木材，按你的人數每人獲得1食物，另加1蘆葦。'},
  {type:'occ', deck:'A', p:3, en:'Animal Dealer', zh:'牲畜商人',
   txt:'Each time you use the "Sheep Market", "Pig Market", or "Cattle Market" accumulation space, you can buy 1 additional animal of the respective type for 1 food.',
   txz:'每次你使用「綿羊市場」、「野豬市場」或「牛市場」累積格時，你可以支付1食物，額外購買1隻相應動物。'},
  {type:'occ', deck:'A', p:4, en:'Lutenist', zh:'魯特琴手',
   txt:'Each time another player uses the "Traveling Players" accumulation space, you get 1 food and 1 wood. Immediately after, you can buy exactly 1 vegetable for 2 food.',
   txz:'每次其他玩家使用「巡迴藝人」累積格時，你獲得1食物和1木材。之後你可以立即以2食物購買恰好1蔬菜。'},
  {type:'occ', deck:'A', p:3, en:'Braggart', zh:'吹噓者',
   txt:'During the scoring, you get 2/3/4/5/7/9 bonus points for having at least 5/6/7/8/9/10 improvements in front of you.',
   txz:'計分時，若你面前有至少5/6/7/8/9/10張發展卡，你獲得2/3/4/5/7/9獎勵分。'},
  {type:'occ', deck:'A', p:4, en:'Pig Breeder', zh:'養豬人',
   txt:'When you play this card, you immediately get 1 wild boar. Your wild boar breed at the end of round 12 (if there is room for new wild boar).',
   txz:'打出這張卡時，你立即獲得1野豬。你的野豬會在第12回合結束時繁殖（前提是有空間容納新野豬）。'},
  {type:'occ', deck:'A', p:1, en:'Wood Cutter', zh:'伐木工',
   txt:'Each time you use a wood accumulation space, you get 1 additional wood.',
   txz:'每次你使用木材累積格時，額外獲得1木材。'},
  {type:'occ', deck:'A', p:1, en:'Hedge Keeper', zh:'樹籬管理員',
   txt:'Each time you use the "Build Fences" action, you do not have to pay wood for 3 of the fences you build.',
   txz:'每次你使用「建柵欄」行動時，其中3條柵欄無需支付木材。'},
  {type:'occ', deck:'A', p:1, en:'Firewood Collector', zh:'柴火收集者',
   txt:'Each time you use the "Farmland", "Grain Seeds", "Grain Utilization", or "Cultivation" action space, at the end of that turn, you get 1 wood.',
   txz:'每次你使用「農田」、「穀物種子」、「穀物利用」或「耕作」行動格時，該人物回合結束時獲得1木材。'},
  {type:'occ', deck:'A', p:1, en:'Scythe Worker', zh:'鐮刀手',
   txt:'When you play this card, you immediately get 1 grain. In the field phase of each harvest, you can harvest 1 additional grain from each of your grain fields.',
   txz:'打出這張卡時，你立即獲得1穀物。每次收成的農田階段，你的每塊穀物田可額外收割1穀物。'},
  {type:'occ', deck:'A', p:1, en:'Seasonal Worker', zh:'季節工',
   txt:'Each time you use the "Day Laborer" action space, you get 1 additional grain. From round 6 on, you can choose to get 1 vegetable instead.',
   txz:'每次你使用「散工」行動格時，額外獲得1穀物。從第6回合起，你可改為獲得1蔬菜。'},
  {type:'occ', deck:'A', p:1, en:'Clay Hut Builder', zh:'泥屋建造者',
   txt:'Once you no longer live in a wooden house, place 2 clay on each of the next 5 round spaces. At the start of these rounds, you get that clay.',
   txz:'當你不再住在木屋時，在接下來5個回合格各放2黏土。這些回合開始時，你獲得該黏土。'},
  {type:'occ', deck:'A', p:1, en:'Grocer', zh:'雜貨商',
   txt:'Pile goods in the order listed on the card. At any time, you can buy the top good for 1 food.',
   txz:'將物資按卡上列出的順序疊放。任何時候，你都可以用1食物購買最頂的一件物資。'},
  {type:'occ', deck:'A', p:1, en:'Stable Architect', zh:'馬廄建築師',
   txt:'During scoring, you get 1 bonus point for each unfenced stable in your farmyard.',
   txz:'計分時，你農場上每個未圍柵欄的馬廄為你帶來1獎勵分。'},
  {type:'occ', deck:'A', p:1, en:'Wall Builder', zh:'築牆工',
   txt:'Each time you build at least 1 room, you can place 1 food on each of the next 4 round spaces. At the start of these rounds, you get that food.',
   txz:'每次你建造至少1個房間時，可在接下來4個回合格各放1食物。這些回合開始時，你獲得該食物。'},
  {type:'occ', deck:'A', p:1, en:'Rough Caster', zh:'粗灰泥匠',
   txt:'Each time you build at least 1 clay room or renovate your house from clay to stone, you also get 3 food.',
   txz:'每次你建造至少1個黏土房間，或將房屋由黏土翻新為石頭時，你額外獲得3食物。'},
  {type:'occ', deck:'A', p:1, en:'Adoptive Parents', zh:'養父母',
   txt:'For 1 food, you can take an action with offspring in the same round you get it. If you do, the offspring does not count as "newborn".',
   txz:'支付1食物，你可以讓新生的家庭成員在出生的同一回合就執行行動。這樣做的話，該成員不算「新生兒」。'},
  {type:'occ', deck:'A', p:1, en:'Mushroom Collector', zh:'採菇人',
   txt:'Immediately after each time you use a wood accumulation space, you can exchange 1 wood for 2 food. If you do, place the wood on the accumulation space.',
   txz:'每次你使用木材累積格後，可以立即用1木材換2食物。這樣做的話，把該木材放回該累積格上。'},
  {type:'occ', deck:'A', p:1, en:'Plow Driver', zh:'犁田手',
   txt:'Once you live in a stone house, at the start of each round, you can pay 1 food to plow 1 field.',
   txz:'當你住進石屋後，每回合開始時，你可以支付1食物犁1塊田。'},
  {type:'occ', deck:'A', p:1, en:'Animal Tamer', zh:'馴獸師',
   txt:'When you play this card, you immediately get your choice of 1 wood or 1 grain. Instead of just 1 animal total, you can keep any 1 animal in each room of your house.',
   txz:'打出這張卡時，你立即獲得1木材或1穀物（自選）。你房屋的每個房間都可以飼養1隻動物（而非全屋合共只可養1隻）。'},
  {type:'occ', deck:'A', p:3, en:'Stonecutter', zh:'石匠',
   txt:'Every improvement, room and renovation costs you 1 stone less.',
   txz:'你的每張發展卡、每個房間和每次翻新都少花1石頭。'},
  {type:'occ', deck:'A', p:1, en:'Conservator', zh:'修復師',
   txt:'You can renovate your wooden house directly to stone without renovating to clay first.',
   txz:'你可以將木屋直接翻新為石屋，無需先翻新為黏土屋。'},
  {type:'occ', deck:'A', p:1, en:'Frame Builder', zh:'構架工',
   txt:'Each time you build a room/renovate, but only once per room/action, you can replace exactly 2 clay or 2 stone with 1 wood.',
   txz:'每次你建造房間／翻新時（每個房間／每次行動限一次），可以用1木材代替恰好2黏土或2石頭。'},
  {type:'occ', deck:'A', p:1, en:'Priest', zh:'神父',
   txt:'When you play this card, if you live in a clay house with exactly 2 rooms, you immediately get 3 clay, 2 reed and 2 stone.',
   txz:'打出這張卡時，若你住在恰好2個房間的黏土屋，你立即獲得3黏土、2蘆葦和2石頭。'},
  {type:'occ', deck:'B', p:1, en:'Paper Maker', zh:'造紙匠',
   txt:'Immediately before playing each occupation after this one, you can pay 1 wood total to get 1 food for each occupation you have in front of you.',
   txz:'在打出這張卡之後，每次打出其他職業卡之前，你可以支付合共1木材，按你面前每張職業卡獲得1食物。'},
  {type:'occ', deck:'B', p:4, en:'Storehouse Keeper', zh:'倉庫管理員',
   txt:'Each time you use the "Resource Market" action space, you also get your choice of 1 clay or 1 grain.',
   txz:'每次你使用「資源市場」行動格時，你額外獲得1黏土或1穀物（自選）。'},
  {type:'occ', deck:'B', p:4, en:'Cattle Feeder', zh:'飼牛人',
   txt:'Each time you use the "Grain Seeds" action space, you can also buy 1 cattle for 1 food.',
   txz:'每次你使用「穀物種子」行動格時，你可以額外以1食物購買1牛。'},
  {type:'occ', deck:'B', p:3, en:'Greengrocer', zh:'蔬果商',
   txt:'Each time you use the "Grain Seeds" action space, you also get 1 vegetable.',
   txz:'每次你使用「穀物種子」行動格時，額外獲得1蔬菜。'},
  {type:'occ', deck:'B', p:3, en:'Brushwood Collector', zh:'柴枝收集者',
   txt:'Each time you renovate or build a room, you can replace the required 1 or 2 reed with a total of 1 wood.',
   txz:'每次你翻新房屋或建造房間時，可以用合共1木材代替所需的1或2蘆葦。'},
  {type:'occ', deck:'B', p:1, en:'Consultant', zh:'顧問',
   txt:'When you play this card in a 1-/2-/3-/4-player game, you immediately get 2 grain/3 clay/2 reed/2 sheep.',
   txz:'在1／2／3／4人遊戲中打出這張卡時，你立即獲得2穀物／3黏土／2蘆葦／2綿羊。'},
  {type:'occ', deck:'B', p:3, en:'House Steward', zh:'管家',
   txt:'If there are still 1/3/6/9 complete rounds left to play, you immediately get 1/2/3/4 wood. During scoring, each player with the most rooms gets 3 bonus points.',
   txz:'打出時若尚餘至少1／3／6／9個完整回合，你立即獲得1／2／3／4木材。計分時，房間最多的玩家（可並列）各獲得3獎勵分。'},
  {type:'occ', deck:'B', p:4, en:'Sheep Whisperer', zh:'馴羊師',
   txt:'Add 2, 5, 8, and 10 to the current round and place 1 sheep on each corresponding round space. At the start of these rounds, you get the sheep.',
   txz:'將目前回合數加2、5、8、10，在對應的回合格各放1綿羊。這些回合開始時，你獲得該綿羊。'},
  {type:'occ', deck:'B', p:4, en:'Pastor', zh:'牧師',
   txt:'Once you are the only player to live in a house with only 2 rooms, you immediately get 3 wood, 2 clay, 1 reed, and 1 stone (only once).',
   txz:'當你成為唯一住在只有2個房間房屋的玩家時，你立即獲得3木材、2黏土、1蘆葦和1石頭（僅限一次）。'},
  {type:'occ', deck:'B', p:1, en:'Assistant Tiller', zh:'助耕者',
   txt:'Each time you use the "Day Laborer" action space, you can also plow 1 field.',
   txz:'每次你使用「散工」行動格時，可以額外犁1塊田。'},
  {type:'occ', deck:'B', p:1, en:'Groom', zh:'馬廄僮僕',
   txt:'When you play this card, you immediately get 1 wood. Once you live in a stone house, at the start of each round, you can build exactly 1 stable for 1 wood.',
   txz:'打出這張卡時，你立即獲得1木材。當你住進石屋後，每回合開始時，你可以用1木材建造恰好1個馬廄。'},
  {type:'occ', deck:'B', p:1, en:'Master Bricklayer', zh:'砌磚大師',
   txt:'Each time you build a major improvement, reduce the stone cost by the number of rooms you have built onto your initial house.',
   txz:'每次你建造主要發展卡時，按你在起始房屋以外加建的房間數量，減少所需的石頭。'},
  {type:'occ', deck:'B', p:1, en:'Carpenter', zh:'木匠',
   txt:'Every new room only costs you 3 of the appropriate build resource and 2 reed (e.g. if you live in a wooden house, 3 wood and 2 reed).',
   txz:'你每個新房間只需3個相應建材和2蘆葦（例如住木屋時，即3木材＋2蘆葦）。'},
  {type:'occ', deck:'B', p:1, en:'Small-Scale Farmer', zh:'小農',
   txt:'As long as you live in a house with exactly 2 rooms, at the start of each round, you get 1 wood.',
   txz:'只要你住在恰好2個房間的房屋，每回合開始時獲得1木材。'},
  {type:'occ', deck:'B', p:1, en:'Cottager', zh:'小屋農戶',
   txt:'Each time you use the "Day Laborer" action space, you can also either build exactly 1 room or renovate your house. Either way, you have to pay the cost.',
   txz:'每次你使用「散工」行動格時，可以額外建造恰好1個房間，或翻新房屋。兩者都仍須支付費用。'},
  {type:'occ', deck:'B', p:1, en:'Roof Ballaster', zh:'屋頂壓石工',
   txt:'When you play this card, you can immediately pay 1 food total to receive 1 stone for each room you have.',
   txz:'打出這張卡時，你可以立即支付合共1食物，按你的房間數量每間獲得1石頭。'},
  {type:'occ', deck:'B', p:1, en:'Tutor', zh:'家庭教師',
   txt:'During scoring, you get 1 bonus point for each occupation played after this one.',
   txz:'計分時，在這張卡之後打出的每張職業卡為你帶來1獎勵分。'},
  {type:'occ', deck:'B', p:1, en:'Oven Firing Boy', zh:'燒爐小工',
   txt:'Each time you use a wood accumulation space, you get an additional "Bake Bread" action.',
   txz:'每次你使用木材累積格時，獲得一次額外的「烤麵包」行動。'},
  {type:'occ', deck:'B', p:1, en:'Organic Farmer', zh:'有機農夫',
   txt:'During the scoring, you get 1 bonus point for each pasture containing at least 1 animal while having unused capacity for at least 3 more animals.',
   txz:'計分時，每個至少有1隻動物、且仍可容納至少3隻動物的牧場，為你帶來1獎勵分。'},
  {type:'occ', deck:'B', p:1, en:'Manservant', zh:'男僕',
   txt:'Once you live in a stone house, place 3 food on each remaining round space. At the start of these rounds, you get the food.',
   txz:'當你住進石屋後，在其餘每個回合格各放3食物。這些回合開始時，你獲得該食物。'},
  {type:'occ', deck:'B', p:1, en:'Childless', zh:'無子嗣者',
   txt:'At the start of each round, if you have at least 3 rooms but only 2 people, you get 1 food and 1 crop of your choice (grain or vegetable).',
   txz:'每回合開始時，若你有至少3個房間但只有2個人，你獲得1食物和1個自選作物（穀物或蔬菜）。'},
  {type:'occ', deck:'B', p:1, en:'Geologist', zh:'地質學家',
   txt:'Each time you use the "Forest" or "Reed Bank" accumulation space, you also get 1 clay. In games with 3 or more players, this also applies to the "Clay Pit".',
   txz:'每次你使用「森林」或「蘆葦灘」累積格時，額外獲得1黏土。3人或以上遊戲中，「黏土坑」同樣適用。'},
  {type:'occ', deck:'B', p:1, en:'Scholar', zh:'學者',
   txt:'Once you live in a stone house, at the start of each round, you can play an occupation for an occupation cost of 1 food or a minor improvement (by paying its cost).',
   txz:'當你住進石屋後，每回合開始時，你可以支付1食物打出1張職業卡，或支付費用打出1張次要發展卡。'},
  {type:'occ', deck:'B', p:1, en:'Sheep Walker', zh:'趕羊人',
   txt:'At any time, you can exchange 1 sheep for either 1 wild boar, 1 vegetable, or 1 stone.',
   txz:'任何時候，你都可以用1綿羊交換1野豬、1蔬菜或1石頭。'},

  // ============ MINOR IMPROVEMENTS (48) ============
  {type:'min', deck:'A', p:1, en:'Basket', zh:'籃子', cost:{reed:1},
   txt:'Immediately after each time you use a wood accumulation space, you can exchange 2 wood for 3 food. If you do, place those 2 wood on the accumulation space.',
   txz:'每次你使用木材累積格後，可以立即用2木材換3食物。這樣做的話，把該2木材放回該累積格上。'},
  {type:'min', deck:'A', p:1, en:'Clay Embankment', zh:'黏土堤', cost:{food:1}, trav:true,
   txt:'You immediately get 1 clay for every 2 clay you already have in your supply.',
   txz:'你的儲備中每有2黏土，立即獲得1黏土。'},
  {type:'min', deck:'A', p:1, en:'Large Greenhouse', zh:'大溫室', cost:{wood:2},
   txt:'Add 4, 7, and 9 to the current round and place 1 vegetable on each corresponding space. At the start of these rounds, you get that vegetable.',
   txz:'將目前回合數加4、7、9，在對應的回合格各放1蔬菜。這些回合開始時，你獲得該蔬菜。'},
  {type:'min', deck:'A', p:1, en:"Shepherd's Crook", zh:'牧羊杖', cost:{wood:1},
   txt:'Each time you fence a new pasture covering at least 4 farmyard spaces, you immediately get 2 sheep on this pasture.',
   txz:'每次你新圍出一個覆蓋至少4格農場的牧場時，立即在該牧場獲得2綿羊。'},
  {type:'min', deck:'A', p:1, en:'Manger', zh:'飼料槽', cost:{food:2},
   txt:'During scoring, if your pastures cover at least 6/7/8/10 farmyard spaces, you get 1/2/3/4 bonus points.',
   txz:'計分時，若你的牧場覆蓋至少6／7／8／10格農場，你獲得1／2／3／4獎勵分。'},
  {type:'min', deck:'A', p:1, en:'Sleeping Corner', zh:'睡覺角落', cost:{wood:1}, vp:1,
   txt:'You can use any "Wish for Children" action space even if it is occupied by one other player\'s person.',
   txz:'即使某個「想要小孩」行動格已被一名其他玩家的人佔用，你仍可使用它。'},
  {type:'min', deck:'A', p:1, en:'Clearing Spade', zh:'開墾鏟', cost:{wood:1},
   txt:'At any time, you can move 1 crop from a planted field containing at least 2 crops to an empty field.',
   txz:'任何時候，你可以把1個作物從種有至少2個作物的田，移到一塊空田。'},
  {type:'min', deck:'A', p:1, en:'Wool Blankets', zh:'羊毛毯', cost:{wood:1},
   txt:'During scoring, if you live in a wooden/clay/stone house by then, you get 3/2/0 bonus points.',
   txz:'計分時，若你屆時住在木屋／黏土屋／石屋，你獲得3／2／0獎勵分。'},
  {type:'min', deck:'A', p:1, en:'Canoe', zh:'獨木舟', cost:{wood:2}, vp:1,
   txt:'Each time you use the "Fishing" accumulation space, you get an additional 1 food and 1 reed.',
   txz:'每次你使用「捕魚」累積格時，額外獲得1食物和1蘆葦。'},
  {type:'min', deck:'A', p:1, en:'Big Country', zh:'遼闊鄉間', cost:{},
   txt:'For each complete round left to play, you immediately get 1 bonus point and 2 food.',
   txz:'每剩一個完整回合，你立即獲得1獎勵分和2食物。'},
  {type:'min', deck:'A', p:1, en:'Junk Room', zh:'雜物房', cost:{wood:1, clay:1},
   txt:'Each time after you build an improvement, including this one, you get 1 food.',
   txz:'每次你建造發展卡（包括這張）之後，獲得1食物。'},
  {type:'min', deck:'A', p:1, en:'Drinking Trough', zh:'飲水槽', cost:{clay:1},
   txt:'Each of your pastures (with or without a stable) can hold up to 2 more animals.',
   txz:'你的每個牧場（無論有沒有馬廄）可多容納2隻動物。'},
  {type:'min', deck:'A', p:1, en:'Young Animal Market', zh:'幼畜市場', cost:{sheep:1}, trav:true,
   txt:'You immediately get 1 cattle. (Effectively, you are exchanging 1 sheep for 1 cattle.)',
   txz:'你立即獲得1牛。（實際上是用1綿羊換1牛。）'},
  {type:'min', deck:'A', p:1, en:'Clay Pipe', zh:'陶菸斗', cost:{clay:1},
   txt:'In the returning home phase of each round, if you gained at least 7 building resources in the preceding work phase, you get 2 food.',
   txz:'每回合的回家階段，若你在之前的工作階段獲得了至少7個建築資源，你獲得2食物。'},
  {type:'min', deck:'A', p:1, en:'Lumber Mill', zh:'鋸木廠', cost:{stone:2}, vp:2,
   txt:'Every improvement costs you 1 wood less.',
   txz:'你的每張發展卡少花1木材。'},
  {type:'min', deck:'A', p:1, en:'Shifting Cultivation', zh:'輪耕', cost:{food:2}, trav:true,
   txt:'Immediately plow 1 field.',
   txz:'立即犁1塊田。'},
  {type:'min', deck:'A', p:1, en:'Pond Hut', zh:'池邊小屋', cost:{wood:1}, vp:1,
   txt:'Place 1 food on each of the next 3 round spaces. At the start of these rounds, you get the food.',
   txz:'在接下來3個回合格各放1食物。這些回合開始時，你獲得該食物。'},
  {type:'min', deck:'A', p:1, en:'Corn Scoop', zh:'穀勺', cost:{wood:1},
   txt:'Each time you use the "Grain Seeds" action space, you get 1 additional grain.',
   txz:'每次你使用「穀物種子」行動格時，額外獲得1穀物。'},
  {type:'min', deck:'A', p:1, en:'Rammed Clay', zh:'夯土', cost:{},
   txt:'When you play this card, you immediately get 1 clay. You can use clay instead of wood to build fences.',
   txz:'打出這張卡時，你立即獲得1黏土。你可以用黏土代替木材建柵欄。'},
  {type:'min', deck:'A', p:1, en:'Threshing Board', zh:'打穀板', cost:{wood:1}, vp:1,
   txt:'Each time you use the "Farmland", or "Cultivation" action space, you get an additional "Bake Bread" action.',
   txz:'每次你使用「農田」或「耕作」行動格時，獲得一次額外的「烤麵包」行動。'},
  {type:'min', deck:'A', p:1, en:'Dutch Windmill', zh:'荷蘭風車', cost:{wood:2, stone:2}, vp:2,
   txt:'Each time you take a "Bake Bread" action in a round immediately following a harvest, you get 3 additional food.',
   txz:'每次你在緊接收成之後的回合執行「烤麵包」行動時，額外獲得3食物。'},
  {type:'min', deck:'A', p:1, en:'Stone Tongs', zh:'石鉗', cost:{wood:1},
   txt:'Each time you use a stone accumulation space, you get 1 additional stone.',
   txz:'每次你使用石頭累積格時，額外獲得1石頭。'},
  {type:'min', deck:'A', p:1, en:'Handplow', zh:'手犁', cost:{wood:1},
   txt:'Add 5 to the current round and place 1 field tile on the corresponding round space. At the start of that round, you can plow the field.',
   txz:'將目前回合數加5，在對應的回合格放1塊田板塊。該回合開始時，你可以犁該田。'},
  {type:'min', deck:'A', p:1, en:'Milk Jug', zh:'牛奶壺', cost:{clay:1},
   txt:'Each time any player (including you) uses the "Cattle Market" accumulation space, you get 3 food, and each other player gets 1 food.',
   txz:'每次任何玩家（包括你）使用「牛市場」累積格時，你獲得3食物，其他每位玩家獲得1食物。'},
  {type:'min', deck:'B', p:1, en:'Mantelpiece', zh:'壁爐架', cost:{stone:1},
   txt:'When you play this card, you immediately get 1 bonus point for each complete round left to play. You may no longer renovate your house.',
   txz:'打出這張卡時，每剩一個完整回合，你立即獲得1獎勵分。之後你不能再翻新房屋。'},
  {type:'min', deck:'B', p:1, en:'Herring Pot', zh:'醃鯡魚罐', cost:{clay:1},
   txt:'Each time you use the "Fishing" accumulation space, place 1 food on each of the next 3 round spaces. At the start of these rounds, you get the food.',
   txz:'每次你使用「捕魚」累積格時，在接下來3個回合格各放1食物。這些回合開始時，你獲得該食物。'},
  {type:'min', deck:'B', p:1, en:'Scullery', zh:'洗滌室', cost:{wood:1, clay:1},
   txt:'At the start of each round, if you live in a wooden house, you get 1 food.',
   txz:'每回合開始時，若你住在木屋，獲得1食物。'},
  {type:'min', deck:'B', p:1, en:'Mining Hammer', zh:'礦錘', cost:{wood:1},
   txt:'When you play this card, you immediately get 1 food. Each time you renovate, you can also build a stable without paying wood.',
   txz:'打出這張卡時，你立即獲得1食物。每次你翻新房屋時，可以額外建造1個馬廄而無需支付木材。'},
  {type:'min', deck:'B', p:1, en:'Hard Porcelain', zh:'硬瓷', cost:{clay:1},
   txt:'At any time, you can exchange 2/3/4 clay for 1/2/3 stone.',
   txz:'任何時候，你可以用2／3／4黏土換1／2／3石頭。'},
  {type:'min', deck:'B', p:1, en:'Caravan', zh:'篷車', cost:{wood:3, food:3},
   txt:'This card provides room for 1 person.',
   txz:'這張卡可供1個人居住。'},
  {type:'min', deck:'B', p:1, en:'Loam Pit', zh:'壤土坑', cost:{food:1}, vp:1,
   txt:'Each time you use the "Day Laborer" action space, you also get 3 clay.',
   txz:'每次你使用「散工」行動格時，額外獲得3黏土。'},
  {type:'min', deck:'B', p:1, en:'Loom', zh:'織布機', cost:{wood:2}, vp:1,
   txt:'In the field phase of each harvest, if you have at least 1/4/7 sheep, you get 1/2/3 food. During scoring, you get 1 bonus point for every 3 sheep.',
   txz:'每次收成的農田階段，若你有至少1／4／7綿羊，你獲得1／2／3食物。計分時，每3隻綿羊為你帶來1獎勵分。'},
  {type:'min', deck:'B', p:1, en:'Moldboard Plow', zh:'鏵式犁', cost:{wood:2},
   txt:'Place 2 field tiles on this card. Twice this game, when you use the "Farmland" action space, you can also plow 1 field from this card.',
   txz:'在這張卡上放2塊田板塊。本局中兩次，當你使用「農田」行動格時，可以額外從這張卡犁1塊田。'},
  {type:'min', deck:'B', p:1, en:'Mini Pasture', zh:'迷你牧場', cost:{food:2}, trav:true,
   txt:'Immediately fence a farmyard space, without paying wood for the fences. (If you already have pastures, the new one must be adjacent to an existing one.)',
   txz:'立即圍起1格農場作牧場，柵欄無需支付木材。（若你已有牧場，新牧場必須與現有牧場相鄰。）'},
  {type:'min', deck:'B', p:1, en:'Pitchfork', zh:'乾草叉', cost:{wood:1},
   txt:'Each time you use the "Grain Seeds" action space, if the "Farmland" action space is occupied, you also get 3 food.',
   txz:'每次你使用「穀物種子」行動格時，若「農田」行動格已被佔用，你額外獲得3食物。'},
  {type:'min', deck:'B', p:1, en:'Lasso', zh:'套索', cost:{reed:1},
   txt:'You can place exactly two people immediately after one another if at least one of them uses the "Sheep Market", "Pig Market", or "Cattle Market" accumulation space.',
   txz:'若其中至少一人使用「綿羊市場」、「野豬市場」或「牛市場」累積格，你可以連續放置恰好兩個人。'},
  {type:'min', deck:'B', p:1, en:'Bottles', zh:'瓶子', cost:{clay:2, food:2}, vp:4,
   txt:'For each person you have, you must pay an additional 1 clay and 1 food to play this card.',
   txz:'打出這張卡時，你每有一個人，須額外支付1黏土和1食物。'},
  {type:'min', deck:'B', p:1, en:'Three-Field Rotation', zh:'三田輪作', cost:{wood:2},
   txt:'At the start of the field phase of each harvest, if you have at least 1 grain field, 1 vegetable field, and 1 empty field, you get 3 food.',
   txz:'每次收成的農田階段開始時，若你同時有至少1塊穀物田、1塊蔬菜田和1塊空田，你獲得3食物。'},
  {type:'min', deck:'B', p:1, en:'Market Stall', zh:'市場攤位', cost:{grain:1}, trav:true,
   txt:'You immediately get 1 vegetable. (Effectively, you are exchanging 1 grain for 1 vegetable.)',
   txz:'你立即獲得1蔬菜。（實際上是用1穀物換1蔬菜。）'},
  {type:'min', deck:'B', p:1, en:'Beanfield', zh:'豆田', cost:{food:1}, vp:1,
   txt:'This card is a field that can only grow vegetables.',
   txz:'這張卡是一塊只能種蔬菜的田。'},
  {type:'min', deck:'B', p:1, en:'Butter Churn', zh:'攪乳器', cost:{food:1}, vp:1,
   txt:'In the field phase of each harvest, you get 1 food for every 3 sheep and 1 food for every 2 cattle you have.',
   txz:'每次收成的農田階段，你每有3綿羊獲得1食物，每有2牛獲得1食物。'},
  {type:'min', deck:'B', p:1, en:"Carpenter's Parlor", zh:'木匠工房', cost:{wood:1, stone:1},
   txt:'Wooden rooms only cost you 2 wood and 2 reed each.',
   txz:'你的每個木房間只需2木材和2蘆葦。'},
  {type:'min', deck:'B', p:1, en:'Acorn Basket', zh:'橡實籃', cost:{reed:1},
   txt:'Place 1 wild boar on each of the next 2 round spaces. At the start of these rounds you get the wild boar.',
   txz:'在接下來2個回合格各放1野豬。這些回合開始時，你獲得該野豬。'},
  {type:'min', deck:'B', p:1, en:'Strawberry Patch', zh:'草莓園', cost:{wood:1}, vp:2,
   txt:'Place 1 food on each of the next 3 round spaces. At the start of these rounds, you get the food.',
   txz:'在接下來3個回合格各放1食物。這些回合開始時，你獲得該食物。'},
  {type:'min', deck:'B', p:1, en:'Thick Forest', zh:'茂密森林', cost:{wood:2},
   txt:'Place 1 wood on each remaining even-numbered round space. At the start of these rounds, you get the wood.',
   txz:'在其餘每個雙數回合格各放1木材。這些回合開始時，你獲得該木材。'},
  {type:'min', deck:'B', p:1, en:'Bread Paddle', zh:'麵包鏟', cost:{wood:1},
   txt:'When you play this card, you immediately get 1 food. For each occupation you play, you get an additional "Bake Bread" action.',
   txz:'打出這張卡時，你立即獲得1食物。之後你每打出一張職業卡，獲得一次額外的「烤麵包」行動。'},
  {type:'min', deck:'B', p:1, en:'Brook', zh:'小溪', cost:{},
   txt:'Each time you use one of the four action spaces above the "Fishing" accumulation space, you get 1 additional food.',
   txz:'每次你使用「捕魚」累積格正上方四個行動格之一時，額外獲得1食物。'},
  {type:'min', deck:'B', p:1, en:'Sack Cart', zh:'麻袋推車', cost:{wood:2},
   txt:'Place 1 grain each on the remaining spaces for rounds 5, 8, 11, and 14. At the start of these rounds, you get the grain.',
   txz:'在剩餘的第5、8、11、14回合格各放1穀物。這些回合開始時，你獲得該穀物。'},

  // ============ MAJOR IMPROVEMENTS (10) ============
  {type:'maj', p:1, en:'Fireplace', zh:'火爐', cost:{clay:2}, vp:1,
   txt:'At any time, you can convert goods to food: 1 vegetable → 2 food; 1 sheep → 2, 1 wild boar → 2, 1 cattle → 3 food. Each time you take a "Bake Bread" action, you can convert any number of grain: 1 grain → 2 food.',
   txz:'任何時候，你可以把物資換成食物：1蔬菜→2食物；1綿羊→2、1野豬→2、1牛→3食物。每次執行「烤麵包」行動時，可以轉換任意數量的穀物：每1穀物→2食物。'},
  {type:'maj', p:1, en:'Fireplace', zh:'火爐', cost:{clay:3}, vp:1,
   txt:'At any time, you can convert goods to food: 1 vegetable → 2 food; 1 sheep → 2, 1 wild boar → 2, 1 cattle → 3 food. Each time you take a "Bake Bread" action, you can convert any number of grain: 1 grain → 2 food.',
   txz:'任何時候，你可以把物資換成食物：1蔬菜→2食物；1綿羊→2、1野豬→2、1牛→3食物。每次執行「烤麵包」行動時，可以轉換任意數量的穀物：每1穀物→2食物。'},
  {type:'maj', p:1, en:'Cooking Hearth', zh:'烹飪爐灶', cost:{clay:4}, vp:1, alt:'or return a Fireplace',
   txt:'At any time, you can convert goods to food: 1 vegetable → 3 food; 1 sheep → 2, 1 wild boar → 3, 1 cattle → 4 food. Each time you take a "Bake Bread" action, you can convert any number of grain: 1 grain → 3 food. You can also get this by returning a Fireplace.',
   txz:'任何時候，你可以把物資換成食物：1蔬菜→3食物；1綿羊→2、1野豬→3、1牛→4食物。每次執行「烤麵包」行動時，可以轉換任意數量的穀物：每1穀物→3食物。你也可以退回一個火爐來換取這張卡。'},
  {type:'maj', p:1, en:'Cooking Hearth', zh:'烹飪爐灶', cost:{clay:5}, vp:1, alt:'or return a Fireplace',
   txt:'At any time, you can convert goods to food: 1 vegetable → 3 food; 1 sheep → 2, 1 wild boar → 3, 1 cattle → 4 food. Each time you take a "Bake Bread" action, you can convert any number of grain: 1 grain → 3 food. You can also get this by returning a Fireplace.',
   txz:'任何時候，你可以把物資換成食物：1蔬菜→3食物；1綿羊→2、1野豬→3、1牛→4食物。每次執行「烤麵包」行動時，可以轉換任意數量的穀物：每1穀物→3食物。你也可以退回一個火爐來換取這張卡。'},
  {type:'maj', p:1, en:'Well', zh:'水井', cost:{wood:1, stone:3}, vp:4,
   txt:'Place 1 food on each of the next 5 round spaces. At the start of these rounds, you get the food.',
   txz:'在接下來5個回合格各放1食物。這些回合開始時，你獲得該食物。'},
  {type:'maj', p:1, en:'Clay Oven', zh:'黏土烤爐', cost:{clay:3, stone:1}, vp:2,
   txt:'When you build this, you can immediately take a "Bake Bread" action. Each time you take a "Bake Bread" action, you can convert exactly 1 grain → 5 food.',
   txz:'建造時，你可以立即執行一次「烤麵包」行動。每次執行「烤麵包」行動時，可以將恰好1穀物→5食物。'},
  {type:'maj', p:1, en:'Stone Oven', zh:'石烤爐', cost:{clay:1, stone:3}, vp:3,
   txt:'When you build this, you can immediately take a "Bake Bread" action. Each time you take a "Bake Bread" action, you can convert up to 2 grain: 1 grain → 4 food.',
   txz:'建造時，你可以立即執行一次「烤麵包」行動。每次執行「烤麵包」行動時，最多可轉換2穀物：每1穀物→4食物。'},
  {type:'maj', p:1, en:'Joinery', zh:'細木工坊', cost:{wood:2, stone:2}, vp:2,
   txt:'In each harvest, you can convert exactly 1 wood → 2 food. During scoring, if you have 3/5/7 wood in your supply, you get 1/2/3 bonus points.',
   txz:'每次收成時，你可以將恰好1木材→2食物。計分時，若你的儲備中有3／5／7木材，你獲得1／2／3獎勵分。'},
  {type:'maj', p:1, en:'Pottery', zh:'陶器坊', cost:{clay:2, stone:2}, vp:2,
   txt:'In each harvest, you can convert exactly 1 clay → 2 food. During scoring, if you have 3/5/7 clay in your supply, you get 1/2/3 bonus points.',
   txz:'每次收成時，你可以將恰好1黏土→2食物。計分時，若你的儲備中有3／5／7黏土，你獲得1／2／3獎勵分。'},
  {type:'maj', p:1, en:"Basketmaker's Workshop", zh:'編籃工坊', cost:{reed:2, stone:2}, vp:2,
   txt:'In each harvest, you can convert exactly 1 reed → 3 food. During scoring, if you have 2/4/5 reed in your supply, you get 1/2/3 bonus points.',
   txz:'每次收成時，你可以將恰好1蘆葦→3食物。計分時，若你的儲備中有2／4／5蘆葦，你獲得1／2／3獎勵分。'},

  // ============ ROUND CARDS (14) ============
  // stage: 1–6; rounds: which rounds the stage covers (cards come out in random order within a stage)
  {type:'rnd', stage:1, rounds:'1–4', en:'Major Improvement', zh:'主要發展',
   txt:'Play exactly 1 major or minor improvement (by paying its cost).',
   txz:'支付費用，打出恰好1張主要或次要發展卡。'},
  {type:'rnd', stage:1, rounds:'1–4', en:'Sheep Market', zh:'綿羊市場',
   txt:'Accumulation space: 1 sheep is added every round. Take all sheep on this space.',
   txz:'累積格：每回合加1綿羊。使用時取走此格上所有綿羊。'},
  {type:'rnd', stage:1, rounds:'1–4', en:'Fencing', zh:'建柵欄',
   txt:'Build fences: pay 1 wood for each fence you build (you have a maximum of 15 fences).',
   txz:'建柵欄：每建1條柵欄支付1木材（你最多有15條柵欄）。'},
  {type:'rnd', stage:1, rounds:'1–4', en:'Grain Utilization', zh:'穀物利用',
   txt:'Sow and/or bake bread.',
   txz:'播種和／或烤麵包。'},
  {type:'rnd', stage:2, rounds:'5–7', en:'Family Growth', zh:'家庭成長',
   txt:'Wish for children: family growth (you need room in your house), then you can play 1 minor improvement.',
   txz:'想要小孩：家庭成長（房屋須有空房間），之後你可以打出1張次要發展卡。'},
  {type:'rnd', stage:2, rounds:'5–7', en:'Renovation', zh:'翻新房屋',
   txt:'House redevelopment: renovate your house, then you can play 1 major or minor improvement.',
   txz:'翻新房屋，之後你可以打出1張主要或次要發展卡。'},
  {type:'rnd', stage:2, rounds:'5–7', en:'Western Quarry', zh:'西採石場',
   txt:'Accumulation space: 1 stone is added every round. Take all stone on this space.',
   txz:'累積格：每回合加1石頭。使用時取走此格上所有石頭。'},
  {type:'rnd', stage:3, rounds:'8–9', en:'Vegetable Seeds', zh:'蔬菜種子',
   txt:'Take 1 vegetable.',
   txz:'取1蔬菜。'},
  {type:'rnd', stage:3, rounds:'8–9', en:'Pig Market', zh:'野豬市場',
   txt:'Accumulation space: 1 wild boar is added every round. Take all wild boar on this space.',
   txz:'累積格：每回合加1野豬。使用時取走此格上所有野豬。'},
  {type:'rnd', stage:4, rounds:'10–11', en:'Cattle Market', zh:'牛市場',
   txt:'Accumulation space: 1 cattle is added every round. Take all cattle on this space.',
   txz:'累積格：每回合加1牛。使用時取走此格上所有牛。'},
  {type:'rnd', stage:4, rounds:'10–11', en:'Eastern Quarry', zh:'東採石場',
   txt:'Accumulation space: 1 stone is added every round. Take all stone on this space.',
   txz:'累積格：每回合加1石頭。使用時取走此格上所有石頭。'},
  {type:'rnd', stage:5, rounds:'12–13', en:'Cultivation', zh:'耕作',
   txt:'Plow 1 field and/or sow.',
   txz:'犁1塊田和／或播種。'},
  {type:'rnd', stage:5, rounds:'12–13', en:'Urgent Family Growth', zh:'緊急家庭成長',
   txt:'Wish for children: family growth, even without room in your house.',
   txz:'想要小孩：家庭成長，即使房屋沒有空房間也可進行。'},
  {type:'rnd', stage:6, rounds:'14', en:'Farm Redevelopment', zh:'農場改建',
   txt:'Renovate your house, then you can build fences.',
   txz:'翻新房屋，之後你可以建柵欄。'},
];

// Harvest happens at the end of the last round of each stage: rounds 4, 7, 9, 11, 13 and 14.
// 每個階段的最後一個回合（第4、7、9、11、13、14回合）結束時進行收成。
const STAGE_END = {1:4, 2:7, 3:9, 4:11, 5:13, 6:14};
